# Generated by Django 3.1.2 on 2020-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_no', models.CharField(max_length=50, null=True)),
                ('student_name', models.CharField(max_length=50, null=True)),
                ('father_name', models.CharField(max_length=50, null=True)),
                ('mother_name', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('phone1', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateTimeField()),
                ('caste', models.CharField(max_length=20, null=True)),
                ('subcaste', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
