# Generated by Django 3.1.2 on 2020-11-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201129_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fees',
            new_name='fee',
        ),
        migrations.RenameModel(
            old_name='pays',
            new_name='pay',
        ),
    ]
