# Generated by Django 3.1.2 on 2020-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201201_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='ad_no',
        ),
        migrations.AddField(
            model_name='fee',
            name='college_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fee',
            name='course',
            field=models.CharField(choices=[('ENGINEERING/ARCHITECTURE', 'ENGINEERING/ARCHITECTURE'), ('ENGINEERING SNQ', 'ENGINEERING SNQ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='ayear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='Total_amount',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='amount_paid',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='mode_payment',
            field=models.CharField(choices=[('NEFT', 'NEFT'), ('BANK-TO-BANK', 'BANK-TO-BANK'), ('NETBANKING', 'NETBANKING')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='aadhar',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='address',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='caste',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='father_name',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='mother_name',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='phone1',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='phone2',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='photo',
            field=models.ImageField(blank=True, default=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student_personal',
            name='subcaste',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
    ]
