# Generated by Django 3.1.2 on 2020-12-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201201_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pay',
            new_name='payment',
        ),
    ]
