# Generated by Django 3.1.2 on 2020-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201201_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='college_type',
            field=models.CharField(choices=[('GOVT / AIDED', 'GOVT / AIDED'), ('Deemed / PRIV. Univ', 'Deemed / PRIV. Univ')], max_length=50, null=True),
        ),
    ]
