# Generated by Django 3.1.2 on 2020-12-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201202_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
