# Generated by Django 3.1.2 on 2020-12-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201202_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='fee_id',
            new_name='fee_name',
        ),
    ]
