# Generated by Django 3.1.2 on 2020-12-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201202_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fee',
            name='ayear',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='college_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='fee',
            name='category',
            field=models.CharField(choices=[('Tuition_Fee', 'Tuition_Fee'), ('Miscellaneous_Fee', 'Miscellaneous_Fee'), ('University_Fee', 'University_Fee')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_payment',
            field=models.CharField(choices=[('NEFT', 'NEFT'), ('BANK-TO-BANK', 'BANK-TO-BANK'), ('NETBANKING', 'NETBANKING'), ('CASH', 'CASH')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment recieved', 'recieved'), ('Payment ack', 'Payment ack')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
