# Generated by Django 3.1.2 on 2021-01-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210111_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicDetails',
            new_name='AcademicDetail',
        ),
    ]
