# Generated by Django 3.1.2 on 2021-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210111_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='total_no_working_days',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SessionYearModel',
        ),
    ]
