# Generated by Django 3.1.2 on 2021-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_academicdetail_total_no_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AcademicDetail',
        ),
    ]
