# Generated by Django 3.1.2 on 2021-01-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210111_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='fee',
            new_name='fee_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='tc',
            name='student',
        ),
        migrations.AddField(
            model_name='tc',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
