# Generated by Django 3.1.2 on 2021-01-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210111_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
    ]
